export const WS_FEED_CONNECTION_START = 'WS_FEED_CONNECTION_START';
export const WS_ORDERS_CONNECTION_START = 'WS_ORDERS_CONNECTION_START';
export const WS_CONNECTION_END = 'WS_CONNECTION_END';
export const WS_CONNECTION_SUCCESS = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS = 'WS_GET_ORDERS';
export const WS_GET_USER_ORDERS = 'WS_GET_USER_ORDERS';


